### ISSUE TITLE
npm test fail

### ISSUE THREAD

**Issue by gabrielstuff** [soixantecircuits/bifrost#14]
running `npm test`

```
proxy.js - launchRequest:  http://46.101.182.71/api/item/
/Volumes/Macintosh HD/Users/gabrielstuff/Sources/node/bifrost/node_modules/async/dist/async.js:331
          length = nativeMax(args.length - start, 0),
                   ^

RangeError: Maximum call stack size exceeded
    at max (native)
    at /Volumes/Macintosh HD/Users/gabrielstuff/Sources/node/bifrost/node_modules/async/dist/async.js:331:20
    at /Volumes/Macintosh HD/Users/gabrielstuff/Sources/node/bifrost/node_modules/async/dist/async.js:840:18
    at /Volumes/Macintosh HD/Users/gabrielstuff/Sources/node/bifrost/app/queue.js:42:9
    at /Volumes/Macintosh HD/Users/gabrielstuff/Sources/node/bifrost/node_modules/async/dist/async.js:3781:7
    at Object.q.process (/Volumes/Macintosh HD/Users/gabrielstuff/Sources/node/bifrost/node_modules/async/dist/async.js:2127:19)
    at /Volumes/Macintosh HD/Users/gabrielstuff/Sources/node/bifrost/node_modules/async/dist/async.js:2076:17
    at /Volumes/Macintosh HD/Users/gabrielstuff/Sources/node/bifrost/node_modules/async/dist/async.js:338:29
    at /Volumes/Macintosh HD/Users/gabrielstuff/Sources/node/bifrost/node_modules/async/dist/async.js:840:18
    at /Volumes/Macintosh HD/Users/gabrielstuff/Sources/node/bifrost/app/queue.js:42:9

npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/gabrielstuff/.nvm/versions/v5.12.0/bin/node" "/Users/gabrielstuff/.nvm/versions/v5.12.0/bin/npm" "start"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! bifrost@0.0.1 start: `node $NODE_DEBUG_OPTION app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bifrost@0.0.1 start script 'node $NODE_DEBUG_OPTION app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bifrost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node $NODE_DEBUG_OPTION app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bifrost
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bifrost
npm ERR! There is likely additional logging output above.
```

**Comment by gabrielstuff** [comment]
Make sure that `npm run test` or `yarn run test` run the right series of query in v2.
